### ISSUE TITLE
After Saving QR code image, need send a Broadcast to scan

### ISSUE THREAD

**Issue by laobie** [scola/Qart#1]
```
Uri uri = Uri.fromFile(file);
Intent scannerIntent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, uri);
context.this.sendBroadcast(scannerIntent);
```

> ACTION_MEDIA_SCANNER_SCAN_FILE
> Broadcast Action: Request the media scanner to scan a file and add it to the media database.

After that, I can see the QR code image in my photo album.

**Comment by scola** [comment]
@laobie
Yes, you're right
Can you send a pull request to fix this issue？

**Comment by laobie** [comment]
OK, you have fixed it.
