### ISSUE TITLE
从现有的二维码中读取文本，是否可以选择从图片中设别二维码中的信息？

### ISSUE THREAD

**Issue by vipzrx** [scola/Qart#4]
你好！感谢你的辛苦付出！
从现有二维码生成所需要的文本，现在只能调用后置摄像头，有些情况是手机的app生成二维码。要想提取其中的文本，需要借助其他手机，或者将二维码打印或在其他设备上显示出来，无法借助单个手机完成二维码文本的提取。

1 是否方便实现，从图片的二维码中提取出文本？

2 这个软件的使用还是比较难上手的，所有我建立了一个微信群，方便讨论使用和用户反馈，同时微信也方便用户为您的劳动成果捐赠

3 入群方法：添加微信“  qq123862905 ”  回复 “ Qart交流 ”
![qq123862905-](https://cloud.githubusercontent.com/assets/5094958/19152380/4ba574ea-8c04-11e6-9a86-c9fa752b9ec7.jpg)

也欢迎大家入群，一起交流学习！

**Comment by scola** [comment]
1. 会考虑实现
2. 使用问题， 软件会继续更新，下个版本加入用户引导, 另外多谢好意，咱没考虑接受捐赠
